## this is the code to create the station_meta list used across the website
## for linking station metadata

sec_gen_FTS_params = c("Air_Temp",
                       "RH",
                       "BP",
                       "Wind_Speed",
                       "Wind_Dir",
                       "Pk_Wind_Speed",
                       "Pk_Wind_Dir",
                       "PC_Tipper",
                       "PP_Tipper",
                       "PC_Raw_Pipe",
                       "Snow_Depth",
                       "SWU",
                       "SWL",
                       "LWU",
                       "LWL",
                       "SWE",
                       "Soil_Moisture",
                       "Soil_Temperature",
                       "Batt")

station_meta = list(
  apelake = list(name = "Ape Lake",
                 elevation = 1423,
                 startYear = 2017,
                 lat = 52.134569,
                 lon = -126.262681,
                 params = c("Air_Temp","RH","Wind_Speed","Wind_Dir","Pk_Wind_Speed","Pk_Wind_Dir", "PC_Tipper", "PP_Tipper","PC_Raw_Pipe","PP_Pipe","Snow_Depth","SWE","Solar_Rad","Batt"),
                 logos = column(12, align = "center", style='padding:0px;',
                                logoPics$bcgov_logo,
                                logoPics$hakai_logo,
                                logoPics$bchs_logo,
                                logoPics$bcenv_logo,
                                logoPics$viu_logo,
                                logoPics$canada_logo)),

  claytonfalls = list(name = "Clayton Falls",
                      elevation = 1260,
                      startYear = 2015,
                      lat = 52.280133,
                      lon =-126.891222,
                      params = c("Air_Temp", "RH", "BP", "Wind_Speed", "Wind_Dir", "Pk_Wind_Speed", "Pk_Wind_Dir", "PC_Tipper", "PP_Tipper", "PC_Raw_Pipe", "PP_Pipe", "Snow_Depth", "SWE", "Solar_Rad", "Batt"),
                      logos = column(12, align = "center", style='padding:0px;',

                                     logoPics$bcgov_logo,
                                     logoPics$hakai_logo,
                                     logoPics$bchs_logo,
                                     logoPics$bcenv_logo,
                                     logoPics$viu_logo,
                                     logoPics$canada_logo)),

  datlamen = list(name = "Datlamen Pass",
                  elevation = 287,
                  startYear = 2014,
                  lat = 52.280133,
                  lon =-132.584272,
                  params = c("Air_Temp", "RH", "Wind_Speed", "Wind_Dir", "Pk_Wind_Speed", "PP_Tipper", "Solar_Rad"),
                  logos = column(12, align = "center", style='padding:0px;',

                                 logoPics$bcgov_logo,
                                 logoPics$taan_logo,
                                 logoPics$viu_logo,
                                 logoPics$canada_logo)),

  eastbuxton = list(name = "Buxton East Ridge",
                    elevation = 738,
                    startYear = 2017,
                    lat = 51.59,
                    lon = -127.957,
                    params = c("Air_Temp", "RH", "BP", "Wind_Speed", "Wind_Dir", "PP_Tipper", "PC_Raw_Pipe", "PP_Pipe", "Snow_Depth", "Solar_Rad", "Batt"),
                    logos = column(12, align = "center", style='padding:0px;',

                                   logoPics$bcgov_logo,
                                   logoPics$hakai_logo,
                                   logoPics$hes_logo,
                                   logoPics$viu_logo,
                                   logoPics$canada_logo,
                                   logoPics$bcparks_logo)),

  homathko = list(name = "Homathko",
                  elevation = 1481,
                  startYear = 2018,
                  lat = 51.10187,
                  lon = -124.9502,
                  params = sec_gen_FTS_params,
                  logos = column(12, align = "center", style='padding:0px;',

                                 logoPics$hakai_logo,
                                 logoPics$unbc_logo,
                                 logoPics$bcgov_logo,
                                 logoPics$bcenv_logo,
                                 logoPics$viu_logo,
                                 logoPics$canada_logo)),

  klinaklini = list(name = "Klinaklini",
                    elevation = 1532,
                    startYear = 2018,
                    lat = 51.38002,
                    lon = -125.7695,
                    params = sec_gen_FTS_params,
                    logos = column(12, align = "center", style='padding:0px;',

                                   logoPics$hakai_logo,
                                   logoPics$unbc_logo,
                                   logoPics$bcgov_logo,
                                   logoPics$bcenv_logo,
                                   logoPics$viu_logo,
                                   logoPics$canada_logo)),

  lowercain = list(name = "Cain Lower",
                   elevation = 1260,
                   startYear = 2019,
                   lat = 50.22562,
                   lon = -126.3567,
                   params = c("Air_Temp", "RH", "PC_Tipper", "PP_Tipper", "PC_Raw_Pipe", "PP_Pipe", "Snow_Depth", "SWE", "Solar_Rad", "Batt"),
                   logos = column(12, align = "center", style='padding:0px;',

                                  logoPics$bcgov_logo,
                                  logoPics$mec_logo,
                                  logoPics$geosci_logo,
                                  logoPics$unlimited_logo,
                                  logoPics$westcoast_logo,
                                  logoPics$mtcain_logo,
                                  logoPics$viac_logo,
                                  logoPics$hes_logo,
                                  logoPics$bcenv_logo,
                                  logoPics$viu_logo,
                                  logoPics$canada_logo)),
  machmell = list(name = "Machmell",
                  elevation = 332,
                  startYear = 2017,
                  lat = 51.5931,
                  lon = -126.451,
                  params = c("Air_Temp", "RH", "Wind_Speed", "Wind_Dir", "Pk_Wind_Speed", "PP_Tipper", "Snow_Depth"),
                  logos = column(12, align = "center", style='padding:0px;',

                                 logoPics$bcgov_logo,
                                 logoPics$bcwildfire_logo,
                                 logoPics$viu_logo,
                                 logoPics$canada_logo)),

  machmellkliniklini = list(name = "Machmell Kliniklini",
                            elevation = 1601,
                            startYear = 2017,
                            lat = 51.655581,
                            lon = -126.140744,
                            params = c("Air_Temp", "RH", "Wind_Speed", "Wind_Dir", "Pk_Wind_Speed", "Pk_Wind_Dir", "PC_Tipper", "PP_Tipper", "PC_Raw_Pipe", "PP_Pipe", "Snow_Depth", "SWE", "Solar_Rad", "Batt"),
                            logos = column(12, align = "center", style='padding:0px;',

                                           logoPics$bcgov_logo,
                                           logoPics$hakai_logo,
                                           logoPics$bcenv_logo,
                                           logoPics$viu_logo,
                                           logoPics$canada_logo)),

  mountarrowsmith = list(name = "Mount Arrowsmith",
                         elevation = 1464,
                         startYear = 2016,
                         lat = 49.207203,
                         lon = -124.567056,
                         params = sec_gen_FTS_params,
                         logos = column(12, align = "center", style='padding:0px;',

                                        logoPics$rdn_logo,
                                        logoPics$mabrri_logo,
                                        logoPics$bcgov_logo,
                                        logoPics$bcenv_logo,
                                        logoPics$viu_logo,
                                        logoPics$canada_logo,
                                        logoPics$mosaic_logo)),

  mountcayley = list(name = "Mount Cayley",
                     elevation = 1588,
                     startYear = 2015,
                     lat = 50.070919,
                     lon = -123.277469,
                     params = c("Air_Temp", "RH", "BP", "Wind_Speed", "Wind_Dir", "Pk_Wind_Speed", "Pk_Wind_Dir", "PC_Tipper", "PP_Tipper", "Snow_Depth", "Solar_Rad", "Soil_Moisture", "Batt"),
                     logos = column(12, align = "center", style='padding:0px;',

                                    logoPics$bcgov_logo,
                                    logoPics$bcenv_logo,
                                    logoPics$viu_logo,
                                    logoPics$canada_logo)),

  mountmaya = list(name = "Mount Maya",
                   elevation = 1681,
                   startYear = 2014,
                   lat = 52.287,
                   lon = -126.07,
                   params = c("Air_Temp", "RH", "BP", "Wind_Speed", "Wind_Dir", "Pk_Wind_Speed", "PP_Tipper", "PC_Raw_Pipe", "PP_Pipe", "Snow_Depth", "Solar_Rad", "Batt"),
                   logos = column(12, align = "center", style='padding:0px;',

                                  logoPics$bcgov_logo,
                                  logoPics$hakai_logo,
                                  logoPics$hes_logo,
                                  logoPics$bchs_logo,
                                  logoPics$bcenv_logo,
                                  logoPics$viu_logo,
                                  logoPics$canada_logo)),

  perseverance = list(name = "Perseverance",
                      elevation = 970,
                      startYear = 2019,
                      lat = 49.59356,
                      lon = -125.1313,
                      params = sec_gen_FTS_params,
                      logos = column(12, align = "center", style='padding:0px;',

                                     logoPics$comox_logo,
                                     logoPics$hancock_logo,
                                     logoPics$bcgov_logo,
                                     logoPics$viu_logo,
                                     logoPics$canada_logo)),

  rennellpass = list(name = "Rennell Pass",
                     elevation = 315,
                     startYear = 2011,
                     lat = 53.3434,
                     lon = -132.365,
                     params = c("Air_Temp", "RH", "Wind_Speed", "Wind_Dir", "Pk_Wind_Speed", "PP_Tipper", "Snow_Depth", "Solar_Rad"),
                     logos = column(12, align = "center", style='padding:0px;',

                                    logoPics$bcgov_logo,
                                    logoPics$viu_logo,
                                    logoPics$canada_logo)),

  steph3 = list(name = "Stephanie 3",
                elevation = 1020,
                startYear = 2015,
                lat = 50.3181,
                lon = -126.363,
                params = c("Air_Temp", "RH", "Wind_Speed", "Wind_Dir", "Pk_Wind_Speed", "PP_Tipper", "Snow_Depth", "Solar_Rad", "Lysimeter"),
                logos = column(12, align = "center", style='padding:0px;',

                               logoPics$bcgov_logo,
                               logoPics$viu_logo,
                               logoPics$canada_logo,
                               logoPics$bcts_logo)),

  tetrahedron = list(name = "Tetrahedron", # removed PC_Tipper and PP_pipe 2021-10, cumulative tipper is only 1/2 the actual rate. new bucket has a 2 mm / tip cal and the logger program is set to 1 mm / tiip
                     elevation = 1423,
                     startYear = 2018,
                     lat = 49.599565,
                     lon = -123.606128,
                     params = c("Air_Temp", "RH", "BP", "Wind_Speed", "Wind_Dir", "Pk_Wind_Speed", "Pk_Wind_Dir", "PP_Tipper", "PC_Raw_Pipe", "Snow_Depth", "SWE", "Solar_Rad", "Soil_Moisture", "Soil_Temperature", "Batt"),
                     logos = column(12, align = "center", style='padding:0px;',

                                    logoPics$scrd_logo,
                                    logoPics$bcgov_logo,
                                    logoPics$bcenv_logo,
                                    logoPics$viu_logo,
                                    logoPics$canada_logo)),

  plummerhut = list(name = "Plummer Hut",
                    elevation = 2680,
                    startYear = 2020,
                    lat = 51.37333,
                    lon = -125.16500,
                    params = c("Air_Temp", "RH", "BP", "Wind_Speed", "Wind_Dir", "Pk_Wind_Speed", "Pk_Wind_Dir", "PC_Tipper", "PP_Tipper", "Snow_Depth", "SWU","SWL","LWU","LWL","Batt"),
                    logos = column(12, align = "center", style='padding:0px;',

                                   logoPics$hakai_logo,
                                   logoPics$unbc_logo,
                                   logoPics$bchs_logo,
                                   logoPics$bcgov_logo,
                                   logoPics$bcenv_logo,
                                   logoPics$viu_logo,
                                   logoPics$canada_logo)),

  # this station is imported through the old database the raw col defs are : "logstamp","air_temp","rh","wind_spd","wind_spd_max","wind_dir","snow","swe","rain","precip","lys","bp","solar","solar_sw_upper","solar_sw_lower","solar_lw_upper","solar_lw_lower","battery","total_rain","total_precip","rain_12","rain_24","rain_48","rain_72","precip_12","precip_24","precip_48","precip_72"
  cainridgerun = list(name = "Cain Ridge Run",
                      elevation = 1330,
                      startYear = 2019, # is actually 2011 need to append data, but this is diff station...
                      lat = 50.226500,
                      lon = -126.351500,
                      params = c("Air_Temp", "Wind_Speed", "Pk_Wind_Speed", "Wind_Dir", "Pk_Wind_Dir", "Snow_Depth", "RH", "PP_Tipper", "PC_Tipper", "Solar_Rad", "Batt"),
                      logos = column(12, align = "center", style='padding:0px;',

                                     logoPics$mec_logo,
                                     logoPics$geosci_logo,
                                     logoPics$unlimited_logo,
                                     logoPics$westcoast_logo,
                                     logoPics$mtcain_logo,
                                     logoPics$viac_logo,
                                     logoPics$hes_logo,
                                     logoPics$bcgov_logo,
                                     logoPics$bcenv_logo,
                                     logoPics$viu_logo,
                                     logoPics$canada_logo)),
  uppercruickshank = list(name = "Upper Cruickshank",
                          elevation = 1348,
                          startYear = 2021,
                          lat = 49.668914,
                          lon = -125.360990,
                          params = sec_gen_FTS_params,
                          logos = column(12, align = "center", style='padding:0px;',

                                         logoPics$comox_logo,
                                         logoPics$bcgov_logo,
                                         logoPics$bcenv_logo,
                                         logoPics$mosaic_logo,
                                         logoPics$viu_logo,
                                         logoPics$canada_logo)),
  upperskeena = list(name = "Upper Skeena",
                     elevation = 1546,
                     startYear = 2021,
                     lat = 56.53839,
                     lon = -127.65730,
                     params = sec_gen_FTS_params,
                     logos = column(12, align = "center", style='padding:0px;',

                                    logoPics$gwa_logo,
                                    logoPics$CIRNAC_logo,
                                    logoPics$viu_logo,
                                    logoPics$bcgov_logo,
                                    logoPics$bcenv_logo))
)
